#flutter create --platform=windows .
#https://docs.flutter.dev/development/packages-and-plugins/developing-packages

name: images
description: images

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #插件测试--H:\WORK\flutterplugins\ftools------------
# ftools:
#   path: ../flutterplugins/ftools/
  #--------------

  http: ^0.13.5
  cupertino_icons: ^1.0.2
  async: ^2.9.0

  #路由管理 https://pub.flutter-io.cn/packages/fluro/install
  fluro: ^2.0.3
  #文件选择 https://pub.flutter-io.cn/packages/file_picker
  file_picker: ^4.5.1
  #网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6
  #buffer https://pub.flutter-io.cn/packages/buffer
  buffer: ^1.1.1
  #webview,只支持android-ios https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^3.0.2
  #Shared preferences plugin https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.15
  #toast https://pub.flutter-io.cn/packages/overlay_support
  overlay_support: ^2.1.0
  #sqflite android\ios\macos  https://pub.dev/packages/sqflite
  sqflite: ^2.0.2
  #sqflite_common_ffi android\ios\macos\linux\windows https://pub.dev/packages/sqflite_common_ffi
  sqflite_common_ffi: ^2.1.0+2
  #android需要，不然会报so包找不到 https://pub.flutter-io.cn/packages/sqlite3_flutter_libs
  sqlite3_flutter_libs: ^0.5.7

  #path 路径相关 https://pub.flutter-io.cn/packages/path
  path: ^1.8.1
  #https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.11
  #provider  https://pub.flutter-io.cn/packages/provider
  provider: ^6.0.4
  #MQTT  https://pub.flutter-io.cn/packages/mqtt_client
  mqtt_client: ^9.6.6
  #事件总线 eventbus https://pub.flutter-io.cn/packages/event_bus
  event_bus: ^2.0.0
  #json https://github.com/google/json_serializable.dart/tree/master/example
  json_annotation: ^4.7.0
  #crc https://pub.flutter-io.cn/packages/crclib
  crclib: ^3.0.0
  #util https://pub.flutter-io.cn/packages/basic_utils
  basic_utils: ^4.2.1
  #animations https://pub.flutter-io.cn/packages/animations
  animations: ^2.0.2

  #-------------------------------------------------------------------------------------
  #（windows\maxos\linux）标题栏设置 https://pub.flutter-io.cn/packages/bitsdojo_window
  #bitsdojo_window: ^0.1.2
  #（windows\maxos\linux）https://pub.flutter-io.cn/packages/window_manager
  window_manager: ^0.2.7
  #-------------------------------------------------------------------------------------

  # 压缩与解压： https://pub.flutter-io.cn/packages/archive
  archive: ^3.3.0
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image_builder
  #cached_network_image_builder: ^0.2.0
  #下拉刷新 https://pub.flutter-io.cn/packages/easy_refresh
  easy_refresh: ^3.0.4+4
  #图片fadein https://pub.flutter-io.cn/packages/image_fade
  image_fade: ^0.6.1
  # listview 滚动到指定位置 https://pub.flutter-io.cn/packages/indexed_list_view
  indexed_list_view: ^2.0.2
  # color picker https://pub.flutter-io.cn/packages/flutter_colorpicker
  flutter_colorpicker: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: fonts/AlibabaPuHuiTi-2-55-Regular.ttf
  assets:
    # assets-generator-begin
    #assets/img/bg/*
    - assets/img/bg/bg1.jpeg
    - assets/img/bg/bg2.jpg
    - assets/img/bg/bg3.jpeg
    - assets/img/bg/bg4.jpeg
    - assets/img/bg/bg5.jpeg
    - assets/img/error_img.png
    # assets-generator-end
